### ISSUE TITLE
Flowcheck

### ISSUE THREAD

**Issue by Murkyskate** [MathuriyaSauravAntrazalSolutions/BankManagementSystem#1]
Need to check the flow.

**Comment by Murkyskate** [comment]
I have noticed that you haven't used the concept of package this...cause you are importing POJOs as it is...although it will not affect the file much but try to implement this:)

**Comment by MathuriyaSauravAntrazalSolutions** [comment]
Okay Brother

<https://www.antrazal.com/>
Saurav Mathuriya
Associate Software Engineer

www.antrazal.com

E: ***@***.*** ***@***.***>*
A: 105, Sangam Tower, Church Road, Jaipur, 302001, Rajasthan, India
